language: r
r_packages:
- covr
cache: packages
matrix:
  include:
  - r: bioc-devel
    os: linux
    dist: xenial
    addons:
      apt:
        update: true
        packages:
        - x11proto-xf86vidmode-dev
        - tcl8.5-dev
        - tk8.5-dev
        - xvfb
    script:
    - R CMD build . --resave-data --compact-vignettes=gs+qpdf
    - travis_wait 30 xvfb-run R CMD check *.tar.gz
  - r: release
    os: osx
    osx_image: xcode11
    before_install:
    - brew update
    - brew cask reinstall xquartz
    - brew install tcl-tk
    - brew link --overwrite --force tcl-tk; brew unlink tcl-tk
    before_script:
    - export DISPLAY=:99.0
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8;
      echo ok ) & fi
    script:
    - R CMD build . --resave-data --no-build-vignettes
    - travis_wait 30 R CMD check *.tar.gz --no-build-vignettes
after_success:
- travis_wait 30 Rscript -e 'library(covr);codecov(type="all")'
notifications:
  slack:
    secure: Uh3tQ+OVwQnoBkQsqLNUU2NYCbgY2b2sT5pi2i26wAxNp/JQrYiiXSFwui5lEutiNRc6mNIFUS7w90Oi3sk41S7aLvjm+oDd5XqRC1gbA1smm/190wF1OXxdRZ5DSrbVaBruoLVfaDZ7+PWZEHk5kAT7U/xaNz6hRR+MLDdSsmiNtI8Gjvj3aaDHgsOKUF1L7Z9Jo47hivZeKY9/uqM/jovRqS+yCM1SSx6iJ+msEOC9THhy/z/rLQlCF+yI53MQohlUkhw/YBfEqu7q6hwue7BFLJ/upi0USxCohoOBq8G8o3U83Nmy32fZrklsQt7n0vZylAWMc/xvXxcef6vWCmnQSQae5q3ElEKYY3KKZ4unmdk1H+86JhEOj1b0dp5HCAkmsVbM/UGIL8+aMNk47tAiC4CEwuAI1/Ri/YwC7nINBTEI3FThzSvC/8tkV++52HmgqHzjlYUeeJvjLPsXbZ69qhXWMuYxES2S5OOo5/i651gssL6dvCQkh8Kx0suz0o/iywkcqpSZiKxa0sEgf/6fYOmNRq2o2hK4weK4EbRBtvhOJ3UEd6McCReYSAbPU705MrRvrltd1dxPjGz8UzmXzqqzNugTv4RKME2ZDA1pV+yQEeek0k+En+wuobswmnsfqP52+XlTq4StdEBYB9ZD3+aHV3nfasBd1NX4m/U=
